cartoonizer/urls.py
from django.urls import path
from . import views

app_name="cartoonizer"

urlpatterns = [
	 path('', views.index, name="index"),
	 path('cartoonize/', views.cartoonize, name='cartoonize')
]

webvision/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('logout/', views.logout_view, name="logout2"),
	path('signup/', views.SignUpView.as_view(), name='signup2'),
	path('', include('django.contrib.auth.urls')),
	path('', views.index, name="index"),
	path('face_detector/', include("face_detector.urls")),
	path('cartoonizer/', include("cartoonizer.urls"))
]

cartoonizer/models.py
from django.db import models

# Create your models here.

cartoonizer/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
import numpy as np
import urllib.request as request
from urllib.request import Request
import json
import cv2
import os
import base64

@csrf_exempt	
def index(req):
	if req.user.is_authenticated:
		return render(req, "cartoonizer/index.html")
	else:
		messages.add_message(req, messages.ERROR, "You have to login first")
		return redirect("login")
@csrf_exempt
def cartoonize(req):
	if req.user.is_authenticated:
		# initialize the data dictionary to be returned by the request
		data = {"success": False}
		
		# check to see if this is a post request
		if req.method == "POST":
			
			# check to see if an image was uploaded 
			if req.FILES.get("image", None) is not None:
				
				# grab the uploaded image
				image = _grab_image(stream=req.FILES["image"])
			# otherwise, assume that a URL was passed in
			else:
				
				# grab the URL from the request
				url = req.POST.get("url", None)
				
				# if the URL is None, then return an error
				if url is None:
					data["error"] = "No URL provided."
					return JsonResponse(data)
				
				# load the image and convert
				image = _grab_image(url=url)

			numBilateralFilters = 4
			img_color = image.copy()
			

			for _ in range(numBilateralFilters):
				img_color = cv2.bilateralFilter(img_color, 15, 30, 20)
				
			img_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
			img_blur = cv2.medianBlur(img_gray, 7)

			img_edge = cv2.adaptiveThreshold( img_blur, 2, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 3,2)

			img_painted = cv2.cvtColor(img_edge, cv2.COLOR_GRAY2RGB)
			img_painted = cv2.bitwise_or(img_color, img_painted)
			
			# encode image as base64
			ret, frame_buff = cv2.imencode('.jpg', img_painted)
			frame_b64 = base64.b64encode(frame_buff)

			#added to get rid of b'
			decoded_image = frame_b64.decode("utf-8")
		
		# return a JSON response
		return render(req, 'cartoonizer/result.html', {'image': decoded_image, "success":data["success"]})
		#return HttpResponseRedirect(reverse('face_detector:result',kwargs={'image': frame_b64}))

	else:
		messages.add_message(req, messages.ERROR, "You have to login first")
		return redirect("login")

def _grab_image(path=None, stream=None, url=None):
	
	# if the path is not None, then load the image from disk
	if path is not None:
		image = cv2.imread(path)
	
	# otherwise, the image does not reside on disk
	else:	
		
		# if the URL is not None, then download the image
		if url is not None:
			resp = request.urlopen(Request(url, headers={'User-Agent': 'Mozilla/5.0'}))
			data = resp.read()
		
		# if the stream is not None, then the image has been uploaded
		elif stream is not None:
			data = stream.read()
		
		# convert the image to a NumPy array
		image = np.asarray(bytearray(data), dtype="uint8")

		# read it into OpenCV format
		image = cv2.imdecode(image, cv2.IMREAD_COLOR)
 
	# return the image
	return image

cartoonizer/templates/cartoonizer/index.html
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	{% block title %}
	{% endblock title %}

</head>

<body>
	<nav class="navbar navbar-expand navbar-light bg-light mb-4">
		<a class="navbar-brand" href="/">WebVision</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

			</ul>

			<a class="btn btn-outline-danger" href="{% url 'logout2'%}">Logout</a>
		</div>
	</nav>
	<div class="jumbotron" id="url-input">
		<h1 class="text-center">WebVision Cartoonizer</h1>
		<p class="text-center">Please provide an image url or upload an image and click "Cartoonize" button.</p>
		<div class="row justify-content-center">
			<div class="col-12 col-md-6">
				<form class="row p-2" id="url-form" novalidate action="{% url 'cartoonizer:cartoonize' %}" method="POST">
					<div class="input-group">
						<input type="url" name="url" id="url" class="form-control" autocomplete="off"
							placeholder="Enter image URL" required>
						<div class="input-group-append">
							<button class="btn btn-secondary" id="urlSubmit" type="submit">Cartoonize</button>
						</div>
					</div>
	
				</form>
				<div id="no-url" class="invalid-feedback">Please enter a URL!</div>

			</div>
			
		</div>

		<p class="text-center">Or</p>

		<div class="row justify-content-center">
			<div class="col-12 col-md-6">
				<form class="row p-2 needs-validation justify-content-center" autocomplete="off" id="file-form" method="POST" enctype="multipart/form-data"
				action="{% url 'cartoonizer:cartoonize' %}" method="POST">
				<div class="input-group" id="file-input-group">
					<div class="custom-file">
						<input id="imagefile" name="image" type="file" class="form-control file custom-file-input"
							data-show-preview="false">

						<label class="custom-file-label" for="imagefile">Choose file</label>

					</div>
					
					<div class="input-group-append">
						<button type="submit" class="input-group-button btn btn-secondary"
							id="imageSubmit">Cartoonize</button>
					</div>

					
				
				</div>
				
				</form>
				<div id="no-file" class="invalid-feedback">Please choose an image!</div>
				<div id="wrong-filetype" class="invalid-feedback">Please choose an image file with JPG, PNG or JPEG extentions!</div>

			</div>
			

					

			<script>
				
				$("#urlSubmit").click(function (){
					var givenurl = $("#url").val();
					if (!givenurl) {
						$('#url').addClass("is-invalid");
						$('#no-url').show()

					}else {
						$("#url-form").submit();
					}
					return false;
				});


				$('#imageSubmit').click(function () {
					var imagefile = $("#imagefile").val();
					var extension = imagefile.split('.').pop().toUpperCase();
					if (imagefile.length < 1) {
						$('#imagefile').addClass("is-invalid");
						$('#no-file').show()

					}
					else if (extension != "PNG" && extension != "JPG" && extension != "JPEG") {
						$('#imagefile').addClass("is-invalid");
						$('#wrong-filetype').show()

					}else {
						$("#file-form").submit();
					}
					return false;
					
				});


				// Add the following code if you want the name of the file appear on select
				$(".custom-file-input").on("change", function () {
					$('#imagefile').removeClass("is-invalid");
					$('#url').removeClass("is-invalid");
					$('#no-url').hide()
					$('#no-file').hide()
					$('#wrong-filetype').hide()
					var fileName = $(this).val().split("\\").pop();
					$(this).siblings(".custom-file-label").addClass("selected").html(fileName);
					console.log(fileName)
				});
			</script>
		</div>
	</div>



</body>

cartoonizer/templates/cartoonizer/result.html
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	{% block title %}
	{% endblock title %}

</head>

<body>
<nav class="navbar navbar-expand navbar-light bg-light mb-4">
		<a class="navbar-brand" href="/">WebVision</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

			</ul>

			<a class="btn btn-outline-danger" href="{% url 'logout2'%}">Logout</a>
		</div>
	</nav>
<div class="jumbotron">
		<h1 class="text-center">Detected Faces</h1>
		
		<div class="row justify-content-center">
		<div class="col-12 text-center">
			<img class="img-fluid rounded mx-auto d-block" src="data:image/jpeg;base64, {{image}}">
			<a class="btn btn-info btn-lg m-2" href="data:image/jpeg;base64, {{image}}" download="cartoonized.jpg" role="button">Download Image</a>
		</div>
		

		</div>
		
</div>
</body>