face_detector/urls.py
from django.urls import path
from . import views

app_name="face_detector"

urlpatterns = [
	 path('', views.index, name="index"),
	path('detect/', views.detect, name='detect')
]

webvision/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('logout/', views.logout_view, name="logout2"),
	path('signup/', views.SignUpView.as_view(), name='signup2'),
	path('', include('django.contrib.auth.urls')),
	path('', views.index, name="index"),
	path('face_detector/', include("face_detector.urls")),
	path('cartoonizer/', include("cartoonizer.urls"))
]

face_detector/models.py
from django.db import models

# Create your models here.

class DetectedFace(models.Model):
	face_id = models.IntegerField("face id")

	def __str__(self):
		return self.face_id
	

face_detector/views.py
# import necessary packages
from django.shortcuts import render, redirect
from django.views import generic
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
import numpy as np
import urllib.request as request
from urllib.request import Request
import json
import cv2
import os
from  .models import DetectedFace
import base64

# define the path to the face detector
FACE_DETECTOR_PATH = "{base_path}/cascades/haarcascade_frontalface_default.xml".format(
	base_path=os.path.abspath(os.path.dirname(__file__)))

@csrf_exempt	
def index(req):
	if req.user.is_authenticated:
		return render(req, "face_detector/index.html")
	else:
		messages.add_message(req, messages.ERROR, "You have to login first")
		return redirect("login")

# find faces and draw it on the image
@csrf_exempt
def detect(req):

	if req.user.is_authenticated:
		# initialize the data dictionary to be returned by the request
		data = {"success": False}
		
		# check to see if this is a post request
		if req.method == "POST":
			
			# check to see if an image was uploaded 
			if req.FILES.get("image", None) is not None:
				
				# grab the uploaded image
				image = _grab_image(stream=req.FILES["image"])
				color_image = image.copy()
			# otherwise, assume that a URL was passed in
			else:
				
				# grab the URL from the request
				url = req.POST.get("url", None)
				
				# if the URL is None, then return an error
				if url is None:
					data["error"] = "No URL provided."
					return JsonResponse(data)
				
				# load the image and convert
				image = _grab_image(url=url)
				color_image = image.copy()
			# convert the image to grayscale
			image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
			
			# load the face cascade detector
			detector = cv2.CascadeClassifier(FACE_DETECTOR_PATH)
			
			# and detect faces in the image
			rects = detector.detectMultiScale(image, scaleFactor=1.1, minNeighbors=5,
				minSize=(30, 30), flags=cv2.CASCADE_SCALE_IMAGE)
			
			# draw rectangles on image
			for rect in rects:
				color_image = cv2.rectangle(color_image, (rect[0], rect[1]), (rect[0]+rect[2], rect[1]+rect[3]), (255, 0, 0))

			# construct a list of bounding boxes from the detection
			rects = [(int(x), int(y), int(x + w), int(y + h)) for (x, y, w, h) in rects]
			
			# update the data dictionary with the faces detected
			data.update({"num_faces": len(rects), "faces": rects, "success": True})
			
			# encode image as base64
			ret, frame_buff = cv2.imencode('.jpg', color_image)
			frame_b64 = base64.b64encode(frame_buff)

			#added to get rid of b'
			decoded_image = frame_b64.decode("utf-8")
		
		# return a JSON response
		return render(req, 'face_detector/result.html', {'image': decoded_image, "face_list":data["faces"], "num_faces":data["num_faces"], "success":data["success"]})
		#return HttpResponseRedirect(reverse('face_detector:result',kwargs={'image': frame_b64}))

	else:
		messages.add_message(req, messages.ERROR, "You have to login first")
		return redirect("login")
		
def _grab_image(path=None, stream=None, url=None):
	
	# if the path is not None, then load the image from disk
	if path is not None:
		image = cv2.imread(path)
	
	# otherwise, the image does not reside on disk
	else:	
		
		# if the URL is not None, then download the image
		if url is not None:
			resp = request.urlopen(Request(url, headers={'User-Agent': 'Mozilla/5.0'}))
			data = resp.read()  
		
		# if the stream is not None, then the image has been uploaded
		elif stream is not None:
			data = stream.read()
		
		# convert the image to a NumPy array
		image = np.asarray(bytearray(data), dtype="uint8")

		# read it into OpenCV format
		image = cv2.imdecode(image, cv2.IMREAD_COLOR)
 
	# return the image
	return image


# find faces and returns as json
@csrf_exempt
def detect_with_post(req):
	
	# initialize the data dictionary to be returned by the request
	data = {"success": False}
	
	# check to see if this is a post request
	if req.method == "POST":
		
		# check to see if an image was uploaded 
		if req.FILES.get("image", None) is not None:
			
			# grab the uploaded image
			image = _grab_image(stream=req.FILES["image"])
		
		# otherwise, assume that a URL was passed in
		else:
			
			# grab the URL from the request
			url = req.POST.get("url", None)
			
			# if the URL is None, then return an error
			if url is None:
				data["error"] = "No URL provided."
				return JsonResponse(data)
			
			# load the image and convert
			image = _grab_image(url=url)
		
		# convert the image to grayscale
		image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
		
		# load the face cascade detector
		detector = cv2.CascadeClassifier(FACE_DETECTOR_PATH)
		
		# and detect faces in the image
		rects = detector.detectMultiScale(image, scaleFactor=1.1, minNeighbors=5,
			minSize=(30, 30), flags=cv2.CASCADE_SCALE_IMAGE)
		
		# construct a list of bounding boxes from the detection
		rects = [(int(x), int(y), int(x + w), int(y + h)) for (x, y, w, h) in rects]
		
		# update the data dictionary with the faces detected
		data.update({"num_faces": len(rects), "faces": rects, "success": True})
	
	# return a JSON response
	return JsonResponse(data)

face_detector/templates/face_detector/index.html
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	{% block title %}
	{% endblock title %}

</head>

<body>
	<nav class="navbar navbar-expand navbar-light bg-light mb-4">
		<a class="navbar-brand" href="/">WebVision</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

			</ul>

			<a class="btn btn-outline-danger" href="{% url 'logout2'%}">Logout</a>
		</div>
	</nav>

	<div class="jumbotron" id="url-input">
		<h1 class="text-center">WebVision Face Detector</h1>
		<p class="text-center">Please provide an image url or upload an image and click "Detect faces" button.</p>
		<div class="row justify-content-center">
			<div class="col-12 col-md-6">
				<form class="row p-2" id="url-form" novalidate action="{% url 'face_detector:detect' %}" method="POST">
					<div class="input-group">
						<input type="url" name="url" id="url" class="form-control" autocomplete="off"	placeholder="Enter image URL" required>
						<div class="input-group-append">
							<button class="btn btn-secondary" id="urlSubmit" type="submit">Detect faces</button>
						</div>
					</div>
	
				</form>
				<div id="no-url" class="invalid-feedback">Please enter a URL!</div>

			</div>
			
		</div>

		<p class="text-center">Or</p>

		<div class="row justify-content-center">
			<div class="col-12 col-md-6">
				<form class="row p-2 needs-validation justify-content-center" id="file-form" method="POST" enctype="multipart/form-data"
				action="{% url 'face_detector:detect' %}" method="POST">
				<div class="input-group" id="file-input-group">
					<div class="custom-file">
						<input id="imagefile" name="image" autocomplete="off" type="file" class="form-control file custom-file-input"
							data-show-preview="false">

						<label class="custom-file-label" for="imagefile">Choose file</label>

					</div>
					
					<div class="input-group-append">
						<button type="submit" class="input-group-button btn btn-secondary"
							id="imageSubmit">Detect faces</button>
					</div>

					
				
				</div>
				
				</form>
				<div id="no-file" class="invalid-feedback">Please choose an image!</div>
				<div id="wrong-filetype" class="invalid-feedback">Please choose an image file with JPG, PNG or JPEG extentions!</div>

			</div>
			

					

			<script>
				
				$("#urlSubmit").click(function (){
					var givenurl = $("#url").val();
					if (!givenurl) {
						$('#url').addClass("is-invalid");
						$('#no-url').show()

					}else {
						$("#url-form").submit();
					}
					return false;
				});


				$('#imageSubmit').click(function () {
					var imagefile = $("#imagefile").val();
					var extension = imagefile.split('.').pop().toUpperCase();
					if (imagefile.length < 1) {
						$('#imagefile').addClass("is-invalid");
						$('#no-file').show()

					}
					else if (extension != "PNG" && extension != "JPG" && extension != "JPEG") {
						$('#imagefile').addClass("is-invalid");
						$('#wrong-filetype').show()

					}else {
						$("#file-form").submit();
					}
					return false;
					
				});


				// Add the following code if you want the name of the file appear on select
				$(".custom-file-input").on("change", function () {
					$('#imagefile').removeClass("is-invalid");
					$('#url').removeClass("is-invalid");
					$('#no-url').hide()
					$('#no-file').hide()
					$('#wrong-filetype').hide()
					var fileName = $(this).val().split("\\").pop();
					$(this).siblings(".custom-file-label").addClass("selected").html(fileName);
					console.log(fileName)
				});
			</script>
		</div>
	</div>



</body>

face_detector/templates/face_detector/result.html
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	{% block title %}
	{% endblock title %}

</head>

<body>
<nav class="navbar navbar-expand navbar-light bg-light mb-4">
		<a class="navbar-brand" href="/">WebVision</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

			</ul>

			<a class="btn btn-outline-danger" href="{% url 'logout2'%}">Logout</a>
		</div>
	</nav>
<div class="jumbotron">
		<h1 class="text-center">Detected Faces</h1>
		<div class="row justify-content-center">
		<div class="col-12 col-md-8">
			<img class="img-fluid" src="data:image/jpeg;base64, {{image}}">
		</div>
		
		<div class="col-12 col-md-4">
			<div class="row justify-content-center" style="height: 100%;">
				<div class="col-10 m-2 p-4 border border-primary rounded-lg text-center">
					{% if num_faces > 0 %}
					<h4>Number of faces detected: </h4>
					<h2 class="text-danger">{{num_faces}}</h2>
					<h5>Detected face coordinates:</h5>
					<p class="text-secondary">{{face_list}}</p>
					<a class="btn btn-info btn-lg m-2" href="data:image/jpeg;base64, {{image}}" download="detected_faces.jpg" role="button">Download Image</a>
				{% else %}
					<h3 class="text-danger">No face detected!</h3>
				{% endif %}
				</div>
			</div>
		
		
		</div>
		

		

		</div>
		
</div>
</body>