cartoonizer/urls.py
from django.urls import path
from . import views

app_name="cartoonizer"

urlpatterns = [
	 path('', views.index, name="index"),
	 path('cartoonize/', views.cartoonize, name='cartoonize')
]

face_detector/urls.py
from django.urls import path
from . import views

app_name="face_detector"

urlpatterns = [
	 path('', views.index, name="index"),
	path('detect/', views.detect, name='detect')
]

webvision/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('logout/', views.logout_view, name="logout2"),
	path('signup/', views.SignUpView.as_view(), name='signup2'),
	path('', include('django.contrib.auth.urls')),
	path('', views.index, name="index"),
	path('face_detector/', include("face_detector.urls")),
	path('cartoonizer/', include("cartoonizer.urls"))
]

templates/index.html
{% load static %}
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	{% block title %}
	{% endblock title %}

</head>

<body>
	{% block content %}
	<!--Navbar Starts Here-->
	<nav class="navbar navbar-expand navbar-light bg-light mb-4">
		<a class="navbar-brand" href="/">WebVision</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">

			</ul>

			<a class="btn btn-outline-danger" href="{% url 'logout2'%}">Logout</a>

		</div>
	</nav>
	<div class="jumbotron">
		<h1 class="text-center">Welcome to WebVision!</h1>
			<div class="row justify-content-around" style="padding-top: 40px;">

			  <div class="col-12 col-md-4">
				  <a class="btn btn-primary btn-lg mb-2 w-100" href="{% url 'face_detector:index'%}" role="button">
				<div class="card text-white bg-primary w-100">
					<div class="card-header">Face Detector</div>
					<div class="card-body">
						<h4 class="card-title">Detect faces on an image.</h4>
						
					</div>
				</div>
			</a>
			  </div>
			  <div class="col-12 col-md-4">
				<a class="btn btn-info btn-lg mb-2 w-100" href="{% url 'cartoonizer:index'%}" role="button">
					<div class="card text-white bg-info w-100">
						<div class="card-header">Cartoonizer</div>
						<div class="card-body">
							<h4 class="card-title">Cartoonize an image.</h4>
							
						</div>
					</div>
				</a>
			  </div>
			  <!-- <div class="col-sm">
				<a class="btn btn-success btn-lg" href="#" role="button">
					<div class="card text-white bg-success mb-3" style="max-width: 20rem;">
						<div class="card-header">Emotion Detector</div>
						<div class="card-body">
							<h4 class="card-title">Emotion detection over webcam.</h4>
							
						</div>
					</div>
				</a>
			  </div> -->
			</div>


		<row >
			

		
		
	  </div>

	

	<!--Navbar Ends-->
	{% endblock content%}

	<!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
		integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
		crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
		integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
		crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
		integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
		crossorigin="anonymous"></script>
</body>